// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviePoster;

namespace MoviePoster.Migrations
{
    [DbContext(typeof(MovieContext))]
    [Migration("20230131133234_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviePoster.Models.Film", b =>
                {
                    b.Property<Guid>("FilmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("AgeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("FilmId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            FilmId = new Guid("b5472944-f5a3-49e7-a0f4-2356a2f65fe1"),
                            AgeLimit = 16,
                            Description = "Альпинистка Келли становится свидетелем убийства подруги. Она успевает снять происходящее на камеру, но ее замечают. Девушка отправляется к неприступной скале, надеясь там скрыться от убийц. Но она не подозревает, с какими трудностями ей придется столкнуться во время подъема на вершину и что ее убежище может стать настоящей ловушкой.",
                            Duration = 86,
                            Genre = "Триллер",
                            Name = "На краю",
                            PictureUrl = "https://img.afisha.me/media/340x0s/cover/01/b/na-krayu-2029754.jpg",
                            Price = 14,
                            Rating = 5.5
                        },
                        new
                        {
                            FilmId = new Guid("7342bdb2-ba06-4878-a95f-6ac3fac46dbf"),
                            AgeLimit = 18,
                            Description = "В биотехнологической лаборатории научились клонировать великих исторических деятелей. С тех пор были организованы подпольные аукционы клонов таких личностей как Микеланджело, Галилей и Вивальди. Однако сатанинский культ, который стоит за биолабораторией, интересуют не только деньги, поэтому они похищают Туринскую плащаницу. Заполучив таким образом ДНК, они планируют оплодотворить американку Лауру, чтобы она родила клона Христа, который они хотят преподнести Дьяволу.",
                            Duration = 110,
                            Genre = "Триллер, ужасы",
                            Name = "Заговор дьявола",
                            PictureUrl = "https://img.afisha.me/media/340x0s/cover/05/c/zagovor-dyavola-411199.jpg",
                            Price = 17,
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            FilmId = new Guid("29f56b6d-9026-4e5c-a6d5-71ce24a352aa"),
                            AgeLimit = 12,
                            Description = "Элитный разведчик Орсон Форчун получил новое задание: остановить продажу и распространение смертельного оружия. Но в одиночку ему эту миссию не потянуть. Он вынужден объединиться с лучшими оперативниками мира, а также известным киноактером, который предоставит лихой группе убедительное прикрытие. На кону судьба человечества, но на этот раз супершпионам придется играть по правилам Голливуда.",
                            Duration = 110,
                            Genre = "Триллер, боевик",
                            Name = "Операция «Фортуна»: Искусство Побеждать",
                            PictureUrl = "https://img.afisha.me/media/340x0s/cover/05/d/operaciya-fortuna-iskusstvo-pobezhdat-6735695.jpg",
                            Price = 15,
                            Rating = 6.9000000000000004
                        },
                        new
                        {
                            FilmId = new Guid("779d34c6-8364-4104-9420-7a47b6dd76b8"),
                            AgeLimit = 12,
                            Description = "История жизни и творческого пути короля рок-н-ролла Элвиса Пресли через призму сложных взаимоотношений с его одиозным менеджером, полковником Томом Паркером. Они работали вместе более 20 лет: от начала карьеры Элвиса до его небывалой славы.",
                            Duration = 160,
                            Genre = "Биография, драма",
                            Name = "Элвис",
                            PictureUrl = "https://img.afisha.me/media/340x0s/cover/04/5/elvis-471555.jpg",
                            Price = 9,
                            Rating = 7.2999999999999998
                        },
                        new
                        {
                            FilmId = new Guid("46c50705-c9bc-4f16-a122-49142cb05cb7"),
                            AgeLimit = 16,
                            Description = "Пилоту Броуди Торрансу удаётся успешно посадить повреждённый штормом самолёт на враждебной территории. Вскоре выясняется, что уцелевшим угрожают воинствующие пираты, которые хотят захватить самолёт и его пассажиров в заложники. Пока идут поиски пропавшего самолёта, Броуди должен защитить своих пассажиров, пока не прибудет помощь.",
                            Duration = 100,
                            Genre = "Триллер, боевик",
                            Name = "Крушение",
                            PictureUrl = "https://img.afisha.me/media/340x0s/cover/0b/e/krushenie-593933.jpg",
                            Price = 15,
                            Rating = 7.0
                        });
                });

            modelBuilder.Entity("MoviePoster.Models.Place", b =>
                {
                    b.Property<Guid>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("Hall")
                        .HasColumnType("int");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PlaceId");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            PlaceId = new Guid("bb03b2c7-ca1a-4bfa-bced-a398b9dab90f"),
                            Hall = 1,
                            RowNumber = 1,
                            SeatNumber = 1,
                            Status = true
                        },
                        new
                        {
                            PlaceId = new Guid("24c523fc-7f04-40b2-9496-25d085de0584"),
                            Hall = 1,
                            RowNumber = 1,
                            SeatNumber = 2,
                            Status = true
                        },
                        new
                        {
                            PlaceId = new Guid("b44283ae-a373-4365-b424-7cf6c6e460cd"),
                            Hall = 1,
                            RowNumber = 2,
                            SeatNumber = 1,
                            Status = true
                        },
                        new
                        {
                            PlaceId = new Guid("9e28f3da-c04d-4779-8541-f58dbf0dabe9"),
                            Hall = 1,
                            RowNumber = 2,
                            SeatNumber = 2,
                            Status = true
                        },
                        new
                        {
                            PlaceId = new Guid("23a7b943-5e4c-4304-a3ab-1cda0f58a2a0"),
                            Hall = 2,
                            RowNumber = 1,
                            SeatNumber = 1,
                            Status = true
                        },
                        new
                        {
                            PlaceId = new Guid("e34e7df7-31e1-422e-afb9-a7602c18567b"),
                            Hall = 1,
                            RowNumber = 2,
                            SeatNumber = 1,
                            Status = true
                        });
                });

            modelBuilder.Entity("MoviePoster.Models.ShowDate", b =>
                {
                    b.Property<Guid>("ShowDateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("ShowDateId");

                    b.ToTable("ShowDates");

                    b.HasData(
                        new
                        {
                            ShowDateId = new Guid("9fba56d6-92c7-45b3-a9cb-11f9f861fa25"),
                            Date = new DateTime(2023, 2, 3, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowDateId = new Guid("a950ca74-0487-46a6-a385-192a6dbb14fd"),
                            Date = new DateTime(2023, 2, 3, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowDateId = new Guid("8075e73a-02ae-4b87-b613-cf6d52609e1b"),
                            Date = new DateTime(2023, 2, 3, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ShowDateId = new Guid("0b253034-363c-4773-a2f4-580a64ac8314"),
                            Date = new DateTime(2023, 2, 3, 22, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MoviePoster.Models.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid?>("FilmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PlaceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ShowDateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TicketId");

                    b.HasIndex("FilmId");

                    b.HasIndex("PlaceId");

                    b.HasIndex("ShowDateId");

                    b.HasIndex("UserId", "FilmId", "ShowDateId", "PlaceId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [FilmId] IS NOT NULL AND [ShowDateId] IS NOT NULL AND [PlaceId] IS NOT NULL");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            TicketId = new Guid("18b296d4-8b88-4d79-aacc-3e61f6ff5b0e"),
                            FilmId = new Guid("29f56b6d-9026-4e5c-a6d5-71ce24a352aa"),
                            PlaceId = new Guid("bb03b2c7-ca1a-4bfa-bced-a398b9dab90f"),
                            ShowDateId = new Guid("9fba56d6-92c7-45b3-a9cb-11f9f861fa25")
                        },
                        new
                        {
                            TicketId = new Guid("72560a5e-8839-4255-a8bd-3c6c0bc9ceff"),
                            FilmId = new Guid("29f56b6d-9026-4e5c-a6d5-71ce24a352aa"),
                            PlaceId = new Guid("24c523fc-7f04-40b2-9496-25d085de0584"),
                            ShowDateId = new Guid("9fba56d6-92c7-45b3-a9cb-11f9f861fa25")
                        },
                        new
                        {
                            TicketId = new Guid("d14b456a-5a8b-48f2-91cc-0e72367abbf9"),
                            FilmId = new Guid("29f56b6d-9026-4e5c-a6d5-71ce24a352aa"),
                            PlaceId = new Guid("b44283ae-a373-4365-b424-7cf6c6e460cd"),
                            ShowDateId = new Guid("9fba56d6-92c7-45b3-a9cb-11f9f861fa25")
                        },
                        new
                        {
                            TicketId = new Guid("f8e75076-4a24-4b59-b0ac-3a0623144d0e"),
                            FilmId = new Guid("29f56b6d-9026-4e5c-a6d5-71ce24a352aa"),
                            PlaceId = new Guid("9e28f3da-c04d-4779-8541-f58dbf0dabe9"),
                            ShowDateId = new Guid("9fba56d6-92c7-45b3-a9cb-11f9f861fa25")
                        },
                        new
                        {
                            TicketId = new Guid("93a51970-c1bf-4d95-941b-fc46f7de5238"),
                            FilmId = new Guid("29f56b6d-9026-4e5c-a6d5-71ce24a352aa"),
                            PlaceId = new Guid("23a7b943-5e4c-4304-a3ab-1cda0f58a2a0"),
                            ShowDateId = new Guid("a950ca74-0487-46a6-a385-192a6dbb14fd")
                        },
                        new
                        {
                            TicketId = new Guid("4c679964-f1a0-44b3-8d11-fe2f95611d04"),
                            FilmId = new Guid("29f56b6d-9026-4e5c-a6d5-71ce24a352aa"),
                            PlaceId = new Guid("e34e7df7-31e1-422e-afb9-a7602c18567b"),
                            ShowDateId = new Guid("a950ca74-0487-46a6-a385-192a6dbb14fd")
                        },
                        new
                        {
                            TicketId = new Guid("a20d1f13-8ad5-4658-a6db-534344a5e51e"),
                            FilmId = new Guid("7342bdb2-ba06-4878-a95f-6ac3fac46dbf"),
                            PlaceId = new Guid("23a7b943-5e4c-4304-a3ab-1cda0f58a2a0"),
                            ShowDateId = new Guid("8075e73a-02ae-4b87-b613-cf6d52609e1b")
                        },
                        new
                        {
                            TicketId = new Guid("faef8963-cac2-4794-a4b2-67d419fd7bb1"),
                            FilmId = new Guid("7342bdb2-ba06-4878-a95f-6ac3fac46dbf"),
                            PlaceId = new Guid("e34e7df7-31e1-422e-afb9-a7602c18567b"),
                            ShowDateId = new Guid("8075e73a-02ae-4b87-b613-cf6d52609e1b")
                        },
                        new
                        {
                            TicketId = new Guid("a386c489-67ef-4810-8316-c8bf9a639bfa"),
                            FilmId = new Guid("7342bdb2-ba06-4878-a95f-6ac3fac46dbf"),
                            PlaceId = new Guid("23a7b943-5e4c-4304-a3ab-1cda0f58a2a0"),
                            ShowDateId = new Guid("0b253034-363c-4773-a2f4-580a64ac8314")
                        },
                        new
                        {
                            TicketId = new Guid("e65e4461-8d9e-4c8a-8018-5f96add29c4a"),
                            FilmId = new Guid("7342bdb2-ba06-4878-a95f-6ac3fac46dbf"),
                            PlaceId = new Guid("e34e7df7-31e1-422e-afb9-a7602c18567b"),
                            ShowDateId = new Guid("0b253034-363c-4773-a2f4-580a64ac8314")
                        });
                });

            modelBuilder.Entity("MoviePoster.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MoviePoster.Models.Ticket", b =>
                {
                    b.HasOne("MoviePoster.Models.Film", "Film")
                        .WithMany("Tickets")
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoviePoster.Models.Place", "Place")
                        .WithMany("Tickets")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoviePoster.Models.ShowDate", "ShowDate")
                        .WithMany("Tickets")
                        .HasForeignKey("ShowDateId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MoviePoster.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
